project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Thinking"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  cover-image: bookcover.png
  twitter-card: true
  site-url: https://agrogan1.github.io/multilevel-thinking/
  search: true
  repo-url: https://github.com/agrogan1/multilevel-thinking
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - preliminaries.qmd
    - intro.qmd
    - simulated-multi-country-data.qmd
    - software.qmd
    - conceptual-framework.qmd
    - cross-sectional.qmd
    - longitudinal.qmd
    - conclusion.qmd
    - references.qmd

bibliography: multilevel-thinking.bib

csl: apa.csl

prefer-html: true

format:
  html:
    theme: 
      light: cosmo
      dark: vapor
    execute:
      echo: false
      warning: false
  docx:
    reference-doc: markstat.docx
    execute:
      echo: false
      warning: false



