project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Thinking"
  subtitle: "Using Multilevel Models To Thread The Needle Between Universality and Cultural Specificity in Cross Cultural Research"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  cover-image: bookcover.png
  downloads: [pdf]
  twitter-card: true
  site-url: https://agrogan1.github.io/multilevel-thinking/
  search: true
  repo-url: https://github.com/agrogan1/multilevel-thinking
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - license.qmd
    - preliminaries.qmd
    - intro.qmd
    - simulated-multi-country-data.qmd
    - software.qmd
    - conceptual-framework.qmd
    - cross-sectional.qmd
    - longitudinal.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - Stata-for-cross-sectional-MLMs.qmd

bibliography: multilevel-thinking.bib

csl: apa.csl

prefer-html: true

format:
  html:
    theme: 
      light: cosmo
      dark: vapor
    css: multilevel-thinking.css
    execute:
      echo: false
      warning: false
  docx:
    reference-doc: markstat.docx
    execute:
      echo: false
      warning: false
  pdf:
    execute:
      echo: false
      warning: false    
      
      

