---
title: "About the Author"
about:
  template: trestles
  links:
    - icon: emoji-smile
      text: Personal Website
      href: https://agrogan1.github.io/
    - icon: house
      text: Faculty Website
      href: https://ssw.umich.edu/faculty/profiles/tenure-track/agrogan
---

I am the Sandra K. Danziger Collegiate Professor of Social Work at the University of Michigan School of Social Work.

My interests are in developing more knowledge to reduce violence against children and Adverse Childhood Experiences (ACEs), with the aim of improving child and family well-being. It is my hope that a better understanding of how to reduce violence against children, and how to reduce ACEs, will contribute to a better understanding of how to improve mental health and well-being across the lifespan. In this research I try to understand the family and community origins of aggression, antisocial behavior, anxiety and depression across diverse communities and contexts. My current research focuses on parenting and child development using international data. I try to understand these issues within the context of current conversations about children’s rights.

A particular focus of my work has been to examine the outcomes of physical punishment. Working closely with many colleagues, we have shown that physical punishment is associated with a wide variety of negative outcomes. This finding remains true even in contexts when physical punishment is used minimally, or when used in ostensibly "normative" ways. We have investigated these associations across diverse communities and countries. Lastly, we have worked to demonstrate more "causally robust" associations between physical punishment and undesirable child outcomes using a variety of quantitative methods.

A more recent stream of research examines a broader range of parenting behaviors, with particular emphasis on "positive parenting" strategies.

I teach courses mostly in the area of statistics, quantitative methods and data visualization.
