# Acknowledgements {.unnumbered}  

No good learning happens without community. At least, that has always been true for me. I am grateful for many creative and energizing discussions with the other members of the MICS (UNICEF data) research team: Professor Julie Ma, Dr. Kaitlin Ward, Professor Garrett Pace and Professor Shawna Lee. I'm thankful for their collegiality, their friendship, their patience with me, and their dedication to good science. Working with these colleagues has greatly deepened my understanding of multilevel models. I'm also very grateful to one of my mentors, Professor Sandra Danziger, who has taught me so much about the *what* and the *why* of mentoring, teaching, and doing research. My colleagues Professor Karen Staller, and Professor Julie Ribaudo have also helped me clarify my thinking about the *what* and the *why* of research and teaching, and have encouraged me along the way. Don Deutsch showed ongoing interest in the development of this book, and has asked some hard questions that have improved its logic. Thank you to Professor Jim Allen for our discussions about how quantitative methods can better listen to lived experience. Importantly, I'd like to express gratitude to the many students in my class on *Multilevel and Longitudinal Modeling* who over the years have helped me think more deeply about statistical and substantive issues, including Dr. Kaitlin Ward, Professor Garrett Pace, Professor Julie Ma, Professor Yoonsun Han, Professor Berenice Castillo, Professor Maria Galano, Dr. Sara Stein, Madhur Singh, and Tong Suo. Thank you for the many valuable discussions during class breaks, and after class. These discussions have also greatly extended my understanding of multilevel models. I'd like to thank Marty Betts and Greg Knollmeyer for their help and support. Most importantly, I have two final people to thank: I'd like to thank Ross Grogan-Kaylor for continued interest in the progress of this book, and many probing thoughtful questions that helped the logic of the presentation. Shari Grogan-Kaylor had many important and challenging questions about the *what* and the *why* of this book, and most importantly to me, *has believed* in it. While I'm thankful for the inspiration and support provided by others, any remaining errors and omissions in this book are of course my responsibility.
