# Conclusion

Many data sets relevant to the study of important social issues, or social problems, are inherently multilevel. For example, data on diverse children in schools, diverse individuals in neighborhoods, and individuals or families in diverse and different countries all have multilevel structures in which individuals are clustered in higher level social structures. Data with repeated measures, sometimes termed panel data, can also be thought of as multilevel data sets, wherein individual timepoints are nested inside individuals, who may in turn be nested or clustered in larger social units such as countries. Failure to use appropriate basic multilevel models with such multilevel data can lead to answers that are either biased, or demonstrably wrong. Simple multilevel models allow the researcher to correctly estimate statistical significance, and to correctly estimate regression coefficients while accounting for multilevel structure. More advanced applications of multilevel models allow the researcher to explore the variation in both predictors and outcomes--and the relationship of predictors to outcomes--and to characterize the extent of this variation. Lastly, multilevel models provide a foundation for thinking about closely related models--fixed effects regression, and correlated random effects models--that provide methods for estimation that afford stronger causal conclusions. Thus, for applied researchers, interested in addressing a variety of social problems and social issues with diverse samples of individuals, multilevel models present a method to think clearly about variation, to explore that variation, and to extend that thinking about variation to estimate more causally robust models within the context of diversity and variation.
