# The Usefulness of Multilevel Modeling and Multilevel Thinking {#sec-multilevel-thinking}

```{r}

library(ggplot2) # beautiful graphs

library(geomtextpath) # path geoms

library(dplyr) # data wrangling

library(tidyr) # data tidying

library(pander) # nice tables

# library(gt) # beautiful tables

library(sf) # simple (spatial) features

# library(leaflet) # beautiful maps

# library(lme4) # MLM

# library(sjPlot) # nice tables for MLM

library(haven) # read and write Stata

# library(Statamarkdown) # run Stata commands

set.seed(3846) # random seed

```

> "I am because we are; and since we are, therefore I am." [@Mbiti1970]

For decades now, multilevel models have been an important quantitative tool for social research. While multilevel models have become very common in social research, there are aspects of these models that are explored less frequently in published articles that appear in academic journals. This book arises from my experiences of teaching a course entitled *Multilevel and Longitudinal Modeling* that I have taught for over a decade in the *Joint Doctoral Program in Social Work and Social Science* at the University of Michigan.

The book started out as a set of notes on *things I only get to discuss during breaks, or after class, or during office hours* in my class on *Multilevel and Longitudinal Modeling*, and has grown from that set of notes into an introduction to multilevel modeling.

My contention is that *multilevel modeling* offers powerful tools for understanding the *multilevel data* that social researchers often confront. For example, researchers are often interested in studying outcomes for diverse groups of children in different schools, residents of diverse and different neighborhoods, or individuals or families living in diverse and different countries. Such inherently multilevel data lead to analytic complexities, some of which appear to me to be well understood, while others seem to be much less often appreciated. 

The point that I wish to make about multilevel data is that when presented with complex multilevel data, failure to use the appropriate multilevel model may lead to conclusions that are demonstrably incorrect. Fortunately, many of these difficulties can be avoided with applications of simple and straightforward multilevel models. \index{correct answers} \index{less wrong}

I start by presenting some initial ideas about multilevel modeling. First, as is relatively commonly understood, *multilevel models allow for the correct estimation of p values in the presence of data clustering*. \index{p values} Second, as is less commonly appreciated, when data are clustered, *multilevel models correctly estimate $\beta$ regression coefficients and may avoid estimating a regression coefficient that is too large, too small, or even has the wrong sign*. \index{sign of coefficients} 

I go on to explore some more complex ideas about multilevel models that I see less often in the published empirical literature. I focus especially on two ideas:  *multilevel models as the exploration of diversity and variation across countries and cultures*; and *multilevel models as a foundation for models that let us think more rigorously about causality*. I argue that multilevel models provide a foundation for engaging with cross-cultural diversity in a quantitatively rigorous fashion. \index{diversity}

Certainly, none of the statistical ideas contained in this book are unique to me. There are thorough--and often much more mathematically rigorous--presentations of many of the ideas contained in this book in some of the excellent foundational texts on multilevel modeling such as the early book by @Raudenbush2002, the excellent book on longitudinal models by @Singer2003, excellent books by @Snijders2012 and @Hox2018, and @RabeHesketh2022's more recent and extremely comprehensive two volume text. @Luke2004, and @Kreft1998, offer shorter, less mathematically rigorous, but still excellent introductions to the topic of multilevel modeling. @Gelman2007 introduced me to the ideas that in this book I describe as "multilevel structure" using an example with voting patterns.

My intent in this book is to offer a kind of accessible tutorial for applied researchers, including especially those who see their research having some advocacy based component. My approach, while offering up some equations, is less mathematically rigorous than some of the above mentioned texts, and written with the intent of providing a clear and practically focused guide for the applied researcher who is attempting to carry out better research with diverse populations, particularly research directed toward advocacy or social change.





