# Introduction

> "Sure, it’s hard to get started; remember learning to use knife and fork? Dig in: you’ll never reach bottom. It’s not like it’s the end of the world--just the world as you think you know it." [@Dove1999]

> "Listening to the world. Well, I did that, and I still do it. I still do it." [Mary Oliver in @Oliver2015] \index{listening}

```{r}

library(ggplot2) # beautiful graphs

library(geomtextpath) # path geoms

library(dplyr) # data wrangling

library(tidyr) # data tidying

```

## Quantitative Methods and Social Justice {#sec-socialjustice}

There is clearly need for both qualitative and quantitative methods. \index{quantitative and qualitative methods} Central to the argument of this book is the idea that advanced quantitative methods can be core contributors to the agenda of understanding issues of diversity and social justice more fully and thoroughly [@Cokley2013; @GroganKaylor2018]. Quantitative methods, particularly in discussions comparing qualitative and quantitative methodologies, are sometimes labelled as inherently *positivist* methods. \index{positivist} My argument regarding this point is twofold. First, there is nothing within the mathematics of quantitative methods that requires a positivist epistemology. Quantitative methodologies could as easily be conducted using a critical epistemology--that is aware of dynamics of power and privilege--as any other methodology [@Stage2014; @Scharrer2021]. \index{quantitative literacy} \index{quantitative criticalism} I note that one of the pioneers of liberation psychology, Martín-Baró [@Aron1994], used both qualitative and quantitative methods [@Martin-Baro1994], including in the latter case, relatively sophisticated arguments about patterns of missing data across a survey data set [@Aron1994]. \index{liberation psychology} \index{Martín-Baró}

Second, when we have samples of a hundred, several hundred, several thousand, or even hundreds of thousands of study participants distributed across multiple and diverse social contexts, it is difficult to imagine a methodology other than a *quantitative* methodology that could accomplish the following: 

1. Sift through thousands of responses, and determine the *overall, or average, pattern of relationships* between risk factors, protective factors, and outcomes.
2. Determine whether there is evidence that the relationships observed within the data are more than *statistical noise*.
3. Adjudicate the *complex multivariate relationships* of risk factors, protective factors and outcomes, while controlling for possible confounding variables, contextual variables, or background variables. 

Additionally, it is difficult to imagine a methodology other than a *quantitative multilevel* methodology that could accomplish the above 3 goals, and could additionally: 

4. Explore the *diversity and variation and commonalities in these relationships* across social contexts. \index{diversity}

Therefore, I consider multilevel modeling to be a principled quantitative method for *listening* to the voices of large numbers of study participants across social contexts. \index{listening} Since graduate school, I have been inspired by the idea of "hearing the other into speech" [@Morton1972]. I believe that when conducted with a critical lens, appropriate multilevel methods can be a way of "hearing others into speech", even with very large data sets. 

Liberation psychology often contains a focus on analyzing society from the *bottom up* [@Montero2009]. According to the liberation psychology perspective, social change in particular is often thought to be most effective when it comes from the bottom up [@Montero2009]. I have not seen this connection made elsewhere, but I have come to believe that by aggregating hundreds, thousands, or even hundreds of thousands of individual responses, and by accounting for, and modeling, the diversity and variation in these responses, that multilevel modeling can be seen as congruent with the liberatory impulse of working from the bottom up. \index{liberation psychology}

In @sec-Simpsons, I consider the way that issues of omitted variables--an often under-appreciated issue--contribute to the difficulty of obtaining *correct* answers in all quantitative work. Dichotomous dependent variables, discussed in @sec-logistic, also add additional complications to the process of obtaining *correct* answers in any kind of regression modeling. In @sec-pvalues, where I consider the estimation of p values, and @sec-multilevelstructure, where I consider the signs of regression coefficients, I explore the ways that *multilevel data* can contribute substantially to the complexity of the analysis of data. This complexity of *multilevel data* means that unless one employs appropriately sophisticated *multilevel analysis* methods with *multilevel data*, one runs a relatively high risk of making *incorrect substantive conclusions*. I thus argue that advanced quantitative methods, like multilevel modeling, can play an important role in helping one to be progressively *less wrong* over time, and in contributing to liberatory ideas and to social justice. \index{less wrong}

There is an ethical argument that is embedded in this book. Many of us do research with the hope of better understanding the relationship of risk and protective factors with outcomes in diverse, and often disadvantaged or marginalized, populations. Many of us further hope that our work might be part of conversations about appropriate policies, programs, treatments or interventions. Given the frequent vulnerability and marginalization of the people with whom we work, when using quantitative methods, it is incumbent upon us to employ methods that adequately address the complexities of the data, that offer an appreciation of the variability and diversity within the data, that provide the most accurate and unbiased estimates possible, and that increase the probability of obtaining *correct* answers to important substantive questions.

> "It is hard to imagine that anyone with a humanitarian worldview would argue against the need for a more quantitatively literate citizenry. Informed political decision-making, retirement planning, active parenting, and the vast majority of choices we make in our personal, occupational, and civic lives can be better served by improved quantitative understanding and reasoning, as well as accompanying action-oriented dispositions." [@Wiest2007]

The idea of this book is that a deeper study of multilevel modeling can result in an advanced "quantitative literacy" [@Wiest2007], \index{quantitative literacy} "quantitative criticalism" [@Scharrer2021], \index{quantitative criticalism} "critical quantitative inquiry" [@Stage2014], \index{critical quantitative inquiry} or "principled argument" [@Abelson1995], \index{principled argument} that is appropriate for drawing accurate conclusions from multilevel data. 

## Some Philosophy of Science {#sec-science}

I am not much of a philosopher of science.  \index{philosophy of science} However, I am very persuaded by Strevens' [-@Strevens2020] minimalist criterion of the "iron rule". In essence, this rule specifies that to count as "science", investigations must engage in "performing an experiment or making an observation that generates relevant empirical evidence" against which competing hypotheses can be tested. A similar perspective is offered by @Goldacre2011 who argues that ideas about interventions should be scrutinized with a "fair test". That is to say, they should be tested against evidence that can support or refute those ideas. I would argue all ideas about promoting human well-being should be able to be subjected to such a "fair test".

I believe that our work—whether qualitative, or quantitative—should strive to be both critical *and* scientific, in the sense that: our research should gather evidence; that evidence should be assessed in order to support, refute, or modify our initial beliefs; and that evidence should be used to think critically about human wellbeing, including dynamics of power and privilege and disparities. With regard to this idea, @ShraderFrechette2014 suggests that a "practical philosophy of science" can contribute both to "speaking truth to power" and to "seeking justice".

Scientific and quantitative thinking are sometimes construed as a *Western*, or even *colonial* activities. \index{philosophy of science} In contrast, I believe and argue that science and quantitative thinking are ways of thinking that are useful for all of us, whenever we encounter the material world, particularly when we desire to confront or address inequities or challenges of that material world. In this light, science and quantitative reasoning might be seen as pan-human cross-cultural activities, allowing human beings to fruitfully engage the material world. In a set of rich descriptions, @Sagan1995 describes the thinking of the !Kung San, \index{"!"Kung San} who use detailed careful and repeated observation of the natural world to construct empirical knowledge that allows them to navigate and survive in the harsh environment of the Kalahari desert. Far from being the domain exclusively of one group of people, @Sagan1995 argues that science is a quintessentially human activity[^ethics]. 

[^ethics]: I'm certainly aware that science--like *any* domain of human thinking--can be misused, and has been misused. The only way to prevent this, I believe, is to couple scientific thinking with rigorous moral reasoning. But that is a subject for a different book!

Similarly, the Islamic scientist @Alhazen_2023, often seen as one of the first exponents of scientific, thinking, described the scientific method in a text from 1000 A.D. The language is unfortunately gendered, which can perhaps be understood given the era of the writing. \index{Alhazen}

> "The seeker after the truth... is not he who studies the writings of the ancients and... puts his trust in them, but rather the one who suspects his faith in them and questions what he gathers from them, the one who submits to argument and demonstration, and not to the sayings of a human being whose nature is fraught with all kinds of imperfection and deficiency." [@Alhazen_2023]

In the approach that I am taking in this book, I believe that there are definite *material realities* of suffering, exploitation, violence, discrimination, and other associated problems that we are trying to understand. 

> "What we see and how we see is of course determined by our perspective, by the place from which we begin our examination of history; but it is determined also by reality itself." [@Martin-Baro1994B] \index{Martín-Baró}

We hope that our understandings will inform efforts for social change. Yet, at the same time we must recognize that our understandings are at best *iterative* and *contingent.* While we will never have a perfect understanding of social reality, we can always improve our understandings, and move in the direction of being *less wrong*. \index{less wrong}

> "... there is no way to know when our observations about complex events in nature are complete. Our knowledge is finite, Karl Popper emphasised, but our ignorance is infinite. ... [W]e can never be certain about the consequences of our interventions, we can only narrow the area of uncertainty. This admission is not as pessimistic as it sounds: claims that resist repeated energetic challenges often turn out to be quite reliable. Such 'working truths' are the building blocks for the reasonably solid structures that support our everyday actions..." [@Silverman1998] \index{Karl Popper}

This recalls the famous saying by the statistician George Box about statistical models, reported in many places, and well captured in the passage below by @Hand2014:

> "In general, when building statistical models, we must not forget that the aim is to understand something about the real world. Or predict, choose an action, make a decision, summarize evidence, and so on, but always about the real world, not an abstract mathematical world: our models are not the reality—a point well made by George Box in his oft-cited remark that 'all models are wrong, but some are useful' (Box, 1979 in @MR0554183)." [@Hand2014] \index{George Box}

A key task then, of using advanced quantitative methods such as multilevel modeling, is to use them to try to be progressively *less wrong* about the answers we are finding to important questions about improving human wellbeing. \index{less wrong}

To reiterate a point made earlier in this chapter, there are many potential complications in data analysis. Omitted variables are an issue that trouble all quantitative research (@sec-Simpsons). Multilevel data provides additional complications in that statistical significance (p values) becomes more difficult to estimate correctly (making false positives more likely) (@sec-pvalues), and without use of appropriate methods, the signs and magnitudes of regression coefficients ($\beta$'s) may be wrong (@sec-multilevelstructure). 

Correct application of multilevel models can help us to be *less wrong* about all of these issues, and to come closer to providing helpful answers to the people we are working with. \index{less wrong}

## A Pragmatic Approach

This book will discuss the ways in which a multilevel statistical perspective not only allows one to appropriately analyze cross cultural or international data, but also the ways in which a multilevel perspective affords the opportunity for more precise quantitative thinking about cross cultural phenomena. The book takes a very pragmatic and very advocacy oriented approach to improving research. \index{pragmatic approach} \index{theory}

> "It shouldn’t be theories that define the problems of our situation, but rather the problems that demand, and so to speak, select, their own theorisation." (@Martin-Baro1998 in @Burton2005).

> "... philosophy can only carry out its critical and creative function in favor of an effective praxis of liberation if it is adequately situated within that liberating praxis, which is independent of philosophy." [@Ellacuria2013]

Following from this pragmatic and advocacy oriented emphasis, the book is largely oriented to the *doing* of quantitative social research with multilevel (or multi-country) data, and is therefore mostly statistical in nature. 

The book moves quickly into detailed statistical arguments. Some of these statistical discussions may seem very technical, or even overly technical. However, an overarching theme of the book is that multilevel data contains hidden complexities. A lack of awareness of the complexities of multilevel data—e.g. complexities of multi-country data—might lead to statistical analyses that point in the wrong direction: yielding false positives; false negatives; or substantively wrong conclusions. 

## Are Answers from Social Science "Obvious"? {#sec-obvious}

Closely related, I think to the idea that quantitative research can advance issues of social justice, is the question of whether answers from social science are "obvious". If social science answers are obvious, then social science has limited abilities to make new discoveries, and to build scientific foundations for evidence. In contrast, if answers from social science are sometimes not obvious, then social science has a greater ability to make new discoveries and build new foundations for evidence. 

I have been thinking a lot about the idea that *Everything Is Obvious, Once You Know The Answer*, as detailed in the book with this title by Duncan @Watts2011. \index{everything is obvious} 

This seems to me especially true in social research. Arguably, some conclusions of social research may indeed be obvious. For example, it may be obvious that *Adverse Childhood Experiences* (ACEs) are associated with long term decreases in mental health. However, even obvious conclusions may need to be quantitatively documented, in order to legitimate programs and interventions, and to secure funding. I also observe that I think that there is often a *historical* dimension to what is considered "obvious": conclusions that are at first considered to be unlikely to be true, or even counter-intuitive, require the weight of accumulating evidence over time for these connections to become "obvious". It is likely that the "obviousness" of the relationship between ACEs and later physical and mental health problems did not become apparent until research began to document these relationships (e.g. @Felitti1998). 

As another example, @Proctor2012 documents the way which smoking was first considered to be an *unlikely* cause of lung cancer; only over the course of several decades of research and discussion to become an *obvious* cause of lung cancer. A similar *historical* dynamic seems to be playing out in some research on parenting and child development. Despite decades of evidence indicating that corporal punishment has undesirable consequences for children [@Gershoff2016], corporal punishment remains a disciplinary strategy endorsed by the majority of the American population [@Hines2022]. 

In contrast sometimes the conclusions of social research may not always be obvious. For example:

1. There has been an ongoing debate about whether corporal punishment is more or less harmful when used by parents in social contexts, or communities where it is more common, or normative, or in contexts that are disadvantaged. @Eamon2001 suggested that "when environmental risk is high, parenting practices that are firmer and higher in control result in lower levels of young adolescent antisocial behavior." This echoes similar research by [@Deater-Deckard1996] suggesting that physical punishment was harmful for European-American children, but not for African-American children. Later, larger sample research has found that this appears not to be the case: physical punishment is harmful for children in *all* groups [@Gershoff2016; @Gershoff2016B; @Pace2019].
2. Using MICS Data [@UNICEF2021], we conducted a study of the link between gender inequality and physical child abuse [@Ma2022]. We expected to find that higher levels of gender inequality led to higher levels of physical abuse for female children, but not for male children. Instead, we found that higher levels of gender inequality were associated with higher levels of physical abuse for *both* male and female children. Additionally, there was some slight evidence that male children were at higher risk of being abused than female children. Equally interesting was that we found that gender inequality was predictive of levels of child abuse, while country level GDP was not.
3. In a study of parenting during Covid-19 [@Lee2022], we expected to find that households with children would experience *higher* levels of anxiety and depression than households without children. Instead, we found the opposite. Being in a household with children was generally *protective* against anxiety and depression. 

In @sec-studyvariation, @sec-pvalues and @sec-multilevelstructure, I provide specific examples of how multilevel data provides even more opportunity to present answers that are *not* obvious.

## Presenting Advanced Statistical Ideas

In presenting advanced, statistical concepts, one is faced with a quandary. One can present statistical concepts in the most general terms, in terms of *x* and *y*. While perhaps the mathematically most general way to present ideas, a highly general (and abstract) presentation risks not being a good way of teaching the ideas, as it is sometimes difficult to apply abstract ideas to one's own specific area of research. 

Alternatively, one can present statistical ideas in terms of specific substantive concepts. The risk of making use of a specific substantive concept is that while concrete examples are always helpful, it may be difficult for the reader to generalize from a specific example to their own area of research.

I ground this presentation in research that we have conducted on parenting and child development in international context [@Grogan-Kaylor2021; @WardA; @WardC; @Ward2023; @Pace2019; @Ma2022]. For the presentation in this book, I use simulated data on these issues.

Using the simulated data, I refer to *predictors* and *outcomes*, and explore the ways that the multilevel model can contribute to understanding how relationships between predictors and outcomes might be similar, or might be different, across *social contexts*. In the examples presented below, I focus on two predictors, parental *warmth*, and parental use of *physical punishment* and focus on the *outcome* of *improved* mental health. I use the social context of different *countries* in our example. 

It is my belief that while I use this specific set of examples, that the idea of studying *families in different countries* is generalizable enough to a multiplicity of diverse contexts, such that the reader can apply these ideas to their own area of interest, whether that be *children in schools*; *residents in neighborhoods*; or *people in different countries*. 

## Research on Parenting and Child Development in International Context

Research on parenting and child development has identified robust associations between parenting behaviors and child developmental outcomes. Broadly speaking, physical punishment is associated with increases in child aggression, child anxiety and child mental health problems [@Gershoff2016], while warm and supportive parenting is associated with decreases in these outcomes [@Rothenberg2022; @Khaleque2002]. However, much of this research is conducted on North American samples [@Henrich2010; @Draper2022]. 

@Barth2020 have argued, that children constitute a class of oppressed persons. If children are oppressed, then it is imperative to empirically determine what factors are promotive of children’s well-being, and what factors constitute risk factors that contribute to decreases in children’s well-being. Equally imperative--given the North American focus of so much research on parenting and child development [@Henrich2010; @Draper2022]--would be efforts to extend the study of parenting and child development to a broader, more global context. As part of such a research agenda, it is necessary to have quantitative tools that are able to determine the consistency of relationships in parenting and child development. That is, are the relationships between certain forms of parenting and child developmental outcomes, largely consistent across countries, largely different across countries, or somewhere in between?

## Universalism And Particularity

> "My conception of the universal is that of a universal enriched by all that is particular, a universal enriched by every particular: the deepening and coexistence of all particulars." [@Cesaire1956]

The specific domain of cross-cultural research on parenting and child development raises more general questions in cross-cultural research of *universalism* and *particularity*. \index{universalism} With regard to child development it is universal that all children need some amount of emotional and material care to grow into healthy youth and healthy adults [@Kottak2021]. Further it is broadly understood that children should be protected from violence [@UNICEF2014]. This broad consensus is manifested in such documents as the Convention on the Rights of the Child [@UN1989] and the United Nations Sustainable Development Goals [@UN2022], representing global efforts to ensure the children are cared for, and are protected against violence.

At the same time, broad international efforts to improve children's well-being must engage with important considerations of cultural uniqueness. Put simply, parenting practices may vary widely between cultural groups [@Gottlieb2002]. Further, what is considered to be beneficial for children in one country or culture may not be considered to be beneficial in all countries or cultures. Similarly, what is considered to be detrimental in one country or culture may not equally be considered to be detrimental in all. Within the area of parenting and child development, most of the debate has focused around the question of whether physical punishment is equally detrimental in all settings, particularly whether physical punishment is detrimental in countries where it is especially common, or normative [@Gershoff2010]. Much less attention has been focused on the study of positive parenting internationally, and the degree to which the outcomes of positive parenting are consistent across countries remains understudied [@ward_grogan-kaylor_ma_pace_lee_2021].

However, as global initiatives to improve child well-being and family life move forward, it becomes increasingly important to continue to collect internationally relevant data about parenting and child outcomes. If recommendations are to be made for policies, interventions, or treatments, such recommendations must be based on accurate balancing of that which is universal against that which is unique to particular cultural contexts. Thus it is necessary to employ statistical methods that are able to adequately and accurately analyze data across countries.

As I will outline below--and is evident in the literature [@Kreft1998; @Raudenbush2002; @Singer2003; @Luke2004; @Snijders2012; @Hox2018; @RabeHesketh2022]--multilevel models are eminently suited for cross-cultural research in that they are not only able to *control for* the clustering of study participants within countries, but are also able to *explore the variation*--or *consistency*--of patterns of social life across countries.

