# Some Preliminary Thoughts {.unnumbered}

> "Like you I 
> 
> Love love, life, the sweet smell of things, the sky-blue landscape of January days.
> 
> ...
> 	
> I believe the world is beautiful.
> 
> And that poetry like bread, is for everyone.
> 	
> And that my veins don’t end in me.
> 
> But in the unanimous blood.
> 
> Of those who struggle for life, 
> 
> Love, little things,
> 
> Landscape and bread, the poetry of everyone."

— [@Dalton2000] (translated By Jack Hirschman) \index{univeralism} \index{variation and diversity}

$~$

> "A lifetime is too narrow to understand it all, beginning with the huge rockshelves that underlie all that life.
> 
> No one ever told us we had to study our lives, make of our lives a study, as if learning natural history or music, that we should begin with the simple exercises first and slowly go on trying  the hard ones, practicing till strength and accuracy became one with the daring ...
> 
> But there come times—perhaps this is one of them—when we have to take ourselves more seriously or die, when we have to pull back from the incantations, rhythms we've moved to thoughtlessly, and disenthrall ourselves, bestow ourselves to silence, or a severer listening ..."

— [@Rich1984]

$~$

> "Research is formalized curiosity. It is poking and prying with a purpose."

— [@Hurston1942]


