---
title: "Models in Multiple Languages"
author: "Andy Grogan-Kaylor"
date: "today"
format:
  html:
    toc: true
    number-sections: true
    code-tools: false
    code-link: true
    theme:
      light: cosmo
      dark: quartz
---

# Setup 

::: {.panel-tabset}

## Stata

```{r}

library(Statamarkdown)

```

## R

```{r}

library(lme4)

```

## Julia

Call Julia from R.

```{r}

library(JuliaCall)

julia_setup(JULIA_HOME = "/Applications/Julia-1.8.app/Contents/Resources/julia/bin")

```

:::

# Get Data & Run Models

::: {.panel-tabset}

## Stata

```{stata}

use simulated_multilevel_data.dta

mixed outcome warmth physical_punishment group HDI || country: warmth

```


## R

```{r}

library(haven)

df <- read_dta("simulated_multilevel_data.dta")

```

```{r}
#| warning: false

fit1 <- lmer(outcome ~ warmth + physical_punishment + 
               group + HDI +
               (1 + warmth || country),
             data = df)

summary(fit1)

```

## Julia

```{julia}
#| output: false

using Tables, MixedModels, StatFiles, DataFrames, CategoricalArrays, DataFramesMeta

df = DataFrame(load("simulated_multilevel_data.dta"))

```

```{julia}
#| output: false

@transform!(df, :country = categorical(:country))

```

```{julia}

m1 = fit(MixedModel, @formula(outcome ~ warmth + physical_punishment + 
               group + HDI +
               (1 + warmth | country)), df)

```

:::

